[package]
name = "snake_macroquad"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--allow-undefined",
    "-C", "link-arg=-z",
    "-C", "link-arg=stack-size=1048576",
]
